hash = ""
hostUser = "harris bisset"
hostEmail = "harrisbisset@gmail.com"

# list of sites below
[[sites]]
slug = "exmpl"
name = "example"
src = "https://www.example.com"
url = "example.com"

[[sites]]
slug = "hb"
name = "harris bisset"
src = "https://bisset.dev"
url = "bisset.dev"

[[sites]]
slug = "dead"
name = "dead link - not real"
src = "https://www.google.com/404"
url = "404"
